-- Add soft delete support for NHATRO
ALTER TABLE NHATRO
  ADD COLUMN IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN DeletedAt DATETIME NULL;

CREATE INDEX IX_NHATRO_IsDeleted ON NHATRO (IsDeleted);
